import { ChangeDetectorRef, OnDestroy } from '@angular/core';
import { BooleanInput } from '@angular/cdk/coercion';
import { PblNgridComponent, PblPaginator } from '@pebula/ngrid';
import * as i0 from "@angular/core";
export declare class PblNgridBsPagination implements OnDestroy {
    private cdr;
    pages: number[];
    pageSizes: number[];
    get pageSizeOptions(): number[];
    set pageSizeOptions(value: number[]);
    get paginator(): PblPaginator<number>;
    set paginator(value: PblPaginator<number>);
    grid: PblNgridComponent<any>;
    get hidePageSize(): boolean;
    set hidePageSize(value: boolean);
    get hideRangeSelect(): boolean;
    set hideRangeSelect(value: boolean);
    private _pageSizeOptions;
    private _paginator;
    private _hidePageSize;
    private _hideRangeSelect;
    constructor(grid: PblNgridComponent<any>, cdr: ChangeDetectorRef);
    ngOnDestroy(): void;
    _pageChanged(page: number): void;
    _perPageChanged(value: string): void;
    private updatePageSizes;
    private handlePageChange;
    static ngAcceptInputType_hidePageSize: BooleanInput;
    static ngAcceptInputType_hideRangeSelect: BooleanInput;
    static ɵfac: i0.ɵɵFactoryDeclaration<PblNgridBsPagination, [{ optional: true; }, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PblNgridBsPagination, "pbl-ngrid-bs-pagination", never, { "pageSizeOptions": "pageSizeOptions"; "paginator": "paginator"; "grid": "grid"; "hidePageSize": "hidePageSize"; "hideRangeSelect": "hideRangeSelect"; }, {}, never, never>;
}
