/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes,extraRequire,missingOverride,missingReturn,unusedPrivateMembers,uselessCode} checked by tsc
 */
/**
 * @record
 */
export function PblColumnTypeDefinitionDataMap() { }
/**
 * Optional value to be used by the template when rendering the cell.
 * Any value is allowed, including functions which allow complex scenarios, for example rendering a cell based on values from other cells.
 * @record
 */
export function PblBaseColumnDefinition() { }
if (false) {
    /**
     * A Unique ID for the column.
     * The ID must be unique across all columns, regardless of the type.
     * Columns with identical ID will share result in identical template.
     *
     * For example, having a header column and a footer column with the same id will result in the same cell presentation for both.
     *
     * > The ID is mandatory. Some implementation might use other values to auto-generate it and some might require it explicitly.
     * This is what it is optional.
     * @type {?|undefined}
     */
    PblBaseColumnDefinition.prototype.id;
    /** @type {?|undefined} */
    PblBaseColumnDefinition.prototype.label;
    /**
     * The type of the values in this column.
     * This is an additional level for matching columns to templates, grouping templates for a type.
     * @type {?|undefined}
     */
    PblBaseColumnDefinition.prototype.type;
    /**
     * CSS class that get applied on the header and cell.
     * You can apply unique header/cell styles using the element name.
     * @type {?|undefined}
     */
    PblBaseColumnDefinition.prototype.css;
    /**
     * The width in px or % in the following format: ##% or ##px
     * Examples: '50%', '50px'
     * @type {?|undefined}
     */
    PblBaseColumnDefinition.prototype.width;
    /**
     * This minimum width in pixels
     * This is an absolute value, thus a number.
     * @type {?|undefined}
     */
    PblBaseColumnDefinition.prototype.minWidth;
    /**
     * This maximum width in pixels
     * This is an absolute value, thus a number.
     * @type {?|undefined}
     */
    PblBaseColumnDefinition.prototype.maxWidth;
    /**
     * A place to store things...
     * This must be an object, values are shadow-copied so persist data between multiple plugins.
     * @type {?|undefined}
     */
    PblBaseColumnDefinition.prototype.data;
}
/**
 * @record
 */
export function PblMetaColumnDefinition() { }
if (false) {
    /**
     * A Unique ID for the column.
     * @type {?}
     */
    PblMetaColumnDefinition.prototype.id;
    /** @type {?} */
    PblMetaColumnDefinition.prototype.kind;
    /**
     * The index (zero based) of the header row this column is attached to, used for multi-header setup.
     * When not set (undefined) the index is considered the LAST index.
     * @type {?}
     */
    PblMetaColumnDefinition.prototype.rowIndex;
}
/**
 * @record
 */
export function PblColumnGroupDefinition() { }
if (false) {
    /**
     * A Unique ID for the column.
     * Auto-generated from the property
     * @type {?|undefined}
     */
    PblColumnGroupDefinition.prototype.id;
    /**
     * The index (zero based) of the header row this header group column is attached to, used for multi-header setup.
     * @type {?}
     */
    PblColumnGroupDefinition.prototype.rowIndex;
    /**
     * The table's column that is the first child column for this group.
     * @type {?}
     */
    PblColumnGroupDefinition.prototype.prop;
    /**
     * The total span of the group (excluding the first child - i.e. prop).
     * The span and prop are used to get the child columns of this group.
     * The span is not dynamic, once the columns are set they don't change.
     *
     * For example, if a we have a span of 2 and the column at the 2nd position is hidden it will still count as
     * being spanned although the UI will span only 1 column... (because the 2nd is hidden...)
     * @type {?}
     */
    PblColumnGroupDefinition.prototype.span;
}
/**
 * @record
 */
export function PblColumnDefinition() { }
if (false) {
    /**
     * A Unique ID for the column.
     * Whe not set (recommend) it is auto-generated by concatenating the values of `prop` and ,
     * If you set this value manually, make sure it does not conflict with other columns!
     * @type {?|undefined}
     */
    PblColumnDefinition.prototype.id;
    /**
     * When set, defines this column as the primary index of the data-set with all values in this column being unique.
     * @type {?|undefined}
     */
    PblColumnDefinition.prototype.pIndex;
    /**
     * The property to display (from the row element)
     * You can use dot notation to display deep paths.
     * @type {?}
     */
    PblColumnDefinition.prototype.prop;
    /** @type {?|undefined} */
    PblColumnDefinition.prototype.headerType;
    /** @type {?|undefined} */
    PblColumnDefinition.prototype.footerType;
    /**
     * A path to a nested object, relative to the row element.
     * The table will display `prop` from the object referenced by `path`.
     *
     * You can also use dot notation directly from `prop`.
     *
     * Example:
     * prop: "street"
     * path: [ "myInstance", "user", "address"
     *
     * is identical to:
     * prop: "myInstance.user.address.street"
     *
     * @type {?|undefined}
     */
    PblColumnDefinition.prototype.path;
    /** @type {?|undefined} */
    PblColumnDefinition.prototype.sort;
    /**
     * A custom predicate function to filter rows using the current column.
     *
     * Valid only when filtering by value.
     * See `PblDataSource.setFilter` for more information.
     * @type {?|undefined}
     */
    PblColumnDefinition.prototype.filter;
    /**
     * Indicates if the table is editable or not.
     * Note that an editable also requires an edit template to qualify as editable, this flag alone is not enough.
     * @type {?|undefined}
     */
    PblColumnDefinition.prototype.editable;
    /** @type {?|undefined} */
    PblColumnDefinition.prototype.pin;
    /**
     * @deprecated BREAKING CHANGE 1.0.0 - Use `alias` instead.
     * @type {?|undefined}
     */
    PblColumnDefinition.prototype.sortAlias;
    /**
     * An alias used to identify the column.
     * Useful when the server provides sort/filter metadata that does not have a 1:1 match with the column names.
     * e.g. Deep path props, property name convention mismatch, etc...
     * @type {?|undefined}
     */
    PblColumnDefinition.prototype.alias;
    /**
     * Optional transformer that control the value output from the combination of a column and a row.
     * The value returned from this transformer will be returned from `PblColumn.getValue`
     * @type {?|undefined}
     */
    PblColumnDefinition.prototype.transform;
}
/**
 * @record
 */
export function PblMetaRowDefinitions() { }
if (false) {
    /** @type {?|undefined} */
    PblMetaRowDefinitions.prototype.rowClassName;
    /** @type {?|undefined} */
    PblMetaRowDefinitions.prototype.type;
}
/**
 * Represent a list of meta column's that together form a META ROW.
 * In other words, this is the definition of a row, using it's building blocks - the columns.
 *
 * > A row in the table represents a row in the datasource, A **meta row** does not, it can represent anything.
 * Meta rows are header, footer and header group.
 * @record
 * @template T
 */
export function PblColumnSet() { }
if (false) {
    /** @type {?} */
    PblColumnSet.prototype.rowIndex;
    /** @type {?} */
    PblColumnSet.prototype.cols;
}
/**
 * Represent a complete column definition set for a table. (table, header, footer and headerGroup columns).
 *
 * `PblNgridColumnDefinitionSet` contains POJO objects (simple JSON like objects) for each column type (`PblColumnDefinition`, `PblMetaColumnDefinition` and `PblColumnGroupDefinition`)
 * which are later used to create runtime instance for each column type (`PblColumn`, `PblMetaColumn` and `PblColumnGroup`)
 *
 * Because `PblNgridColumnDefinitionSet` contains POJO objects it can be serialized easily.
 * @record
 */
export function PblNgridColumnDefinitionSet() { }
if (false) {
    /** @type {?} */
    PblNgridColumnDefinitionSet.prototype.table;
    /** @type {?} */
    PblNgridColumnDefinitionSet.prototype.header;
    /** @type {?} */
    PblNgridColumnDefinitionSet.prototype.footer;
    /** @type {?} */
    PblNgridColumnDefinitionSet.prototype.headerGroup;
}
/**
 * Represent a complete column set for a table. (table, header, footer and headerGroup columns).
 *
 * `PblNgridColumnSet` contains runtime instances of for each column type (`PblColumn`, `PblMetaColumn` and `PblColumnGroup`)
 * which
 * @record
 */
export function PblNgridColumnSet() { }
if (false) {
    /** @type {?} */
    PblNgridColumnSet.prototype.table;
    /** @type {?} */
    PblNgridColumnSet.prototype.header;
    /** @type {?} */
    PblNgridColumnSet.prototype.footer;
    /** @type {?} */
    PblNgridColumnSet.prototype.headerGroup;
    /** @type {?} */
    PblNgridColumnSet.prototype.groupStore;
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidHlwZXMuanMiLCJzb3VyY2VSb290Ijoibmc6Ly9AcGVidWxhL25ncmlkLyIsInNvdXJjZXMiOlsibGliL3RhYmxlL2NvbHVtbnMvdHlwZXMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7OztBQVFBLG9EQUVDOzs7Ozs7QUFlRCw2Q0ErQ0M7Ozs7Ozs7Ozs7Ozs7SUFwQ0MscUNBQVk7O0lBQ1osd0NBQWU7Ozs7OztJQU1mLHVDQUF3Qzs7Ozs7O0lBTXhDLHNDQUFhOzs7Ozs7SUFNYix3Q0FBZTs7Ozs7O0lBS2YsMkNBQWtCOzs7Ozs7SUFLbEIsMkNBQWtCOzs7Ozs7SUFNbEIsdUNBQVc7Ozs7O0FBR2IsNkNBYUM7Ozs7OztJQVRDLHFDQUFXOztJQUVYLHVDQUEwQjs7Ozs7O0lBTTFCLDJDQUFpQjs7Ozs7QUFHbkIsOENBeUJDOzs7Ozs7O0lBcEJDLHNDQUFZOzs7OztJQUtaLDRDQUFpQjs7Ozs7SUFJakIsd0NBQWE7Ozs7Ozs7Ozs7SUFVYix3Q0FBYTs7Ozs7QUFHZix5Q0F3RUM7Ozs7Ozs7O0lBbEVDLGlDQUFZOzs7OztJQUtaLHFDQUFpQjs7Ozs7O0lBTWpCLG1DQUFhOztJQUViLHlDQUE4Qzs7SUFDOUMseUNBQThDOzs7Ozs7Ozs7Ozs7Ozs7O0lBZ0I5QyxtQ0FBZ0I7O0lBRWhCLG1DQUFnQzs7Ozs7Ozs7SUFRaEMscUNBQW1DOzs7Ozs7SUFNbkMsdUNBQW1COztJQUVuQixrQ0FBc0I7Ozs7O0lBSXRCLHdDQUFtQjs7Ozs7OztJQU9uQixvQ0FBZTs7Ozs7O0lBTWYsd0NBQTREOzs7OztBQUc5RCwyQ0FHQzs7O0lBRkMsNkNBQXNCOztJQUN0QixxQ0FBa0M7Ozs7Ozs7Ozs7O0FBU3BDLGtDQUdDOzs7SUFGQyxnQ0FBaUI7O0lBQ2pCLDRCQUFVOzs7Ozs7Ozs7OztBQVdaLGlEQVNDOzs7SUFSQyw0Q0FJRTs7SUFDRiw2Q0FBZ0Q7O0lBQ2hELDZDQUFnRDs7SUFDaEQsa0RBQXNEOzs7Ozs7Ozs7QUFTeEQsdUNBVUM7OztJQVRDLGtDQUlFOztJQUNGLG1DQUFzQzs7SUFDdEMsbUNBQXNDOztJQUN0Qyx3Q0FBNEM7O0lBQzVDLHVDQUFnQyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IERhdGFTb3VyY2VDb2x1bW5QcmVkaWNhdGUsIFBibE5ncmlkU29ydGVyIH0gZnJvbSAnLi4vLi4vZGF0YS1zb3VyY2UvdHlwZXMnO1xuaW1wb3J0IHsgUGJsTWV0YUNvbHVtbiB9IGZyb20gJy4vbWV0YS1jb2x1bW4nO1xuaW1wb3J0IHsgUGJsQ29sdW1uIH0gZnJvbSAnLi9jb2x1bW4nO1xuaW1wb3J0IHsgUGJsQ29sdW1uR3JvdXAsIFBibENvbHVtbkdyb3VwU3RvcmUgfSBmcm9tICcuL2dyb3VwLWNvbHVtbic7XG5cbmV4cG9ydCB0eXBlIE1FVEFfQ09MVU1OX1RZUEVTID0gJ2hlYWRlcicgfCAnaGVhZGVyR3JvdXAnIHwgJ2Zvb3Rlcic7XG5leHBvcnQgdHlwZSBDT0xVTU5fVFlQRVMgPSBNRVRBX0NPTFVNTl9UWVBFUyB8ICd0YWJsZSc7XG5cbmV4cG9ydCBpbnRlcmZhY2UgUGJsQ29sdW1uVHlwZURlZmluaXRpb25EYXRhTWFwIHtcbiAgW3R5cGVOYW1lOiBzdHJpbmddOiBhbnk7XG59XG5cbmV4cG9ydCB0eXBlIFBibENvbHVtblR5cGVEZWZpbml0aW9uPFAgZXh0ZW5kcyBrZXlvZiBQYmxDb2x1bW5UeXBlRGVmaW5pdGlvbkRhdGFNYXAgPSBhbnk+ID0geyBuYW1lOiBQOyBkYXRhPzogUGJsQ29sdW1uVHlwZURlZmluaXRpb25EYXRhTWFwW1BdIH07XG5cbiAgLyoqXG4gICAqIFRoZSB0eXBlIG9mIHRoZSB2YWx1ZXMgaW4gdGhpcyBjb2x1bW4uXG4gICAqIFRoaXMgaXMgYW4gYWRkaXRpb25hbCBsZXZlbCBmb3IgbWF0Y2hpbmcgY29sdW1ucyB0byB0ZW1wbGF0ZXMsIGdyb3VwaW5nIHRlbXBsYXRlcyBmb3IgYSB0eXBlLlxuICAgKi9cbiAgLy8gdHlwZTogc3RyaW5nIHwgO1xuICAvKipcbiAgICogT3B0aW9uYWwgdmFsdWUgdG8gYmUgdXNlZCBieSB0aGUgdGVtcGxhdGUgd2hlbiByZW5kZXJpbmcgdGhlIGNlbGwuXG4gICAqIEFueSB2YWx1ZSBpcyBhbGxvd2VkLCBpbmNsdWRpbmcgZnVuY3Rpb25zIHdoaWNoIGFsbG93IGNvbXBsZXggc2NlbmFyaW9zLCBmb3IgZXhhbXBsZSByZW5kZXJpbmcgYSBjZWxsIGJhc2VkIG9uIHZhbHVlcyBmcm9tIG90aGVyIGNlbGxzLlxuICAgKi9cbiAgLy8gdHlwZURhdGE/OiBhbnk7XG5cbmV4cG9ydCBpbnRlcmZhY2UgUGJsQmFzZUNvbHVtbkRlZmluaXRpb24ge1xuICAvKipcbiAgICogQSBVbmlxdWUgSUQgZm9yIHRoZSBjb2x1bW4uXG4gICAqIFRoZSBJRCBtdXN0IGJlIHVuaXF1ZSBhY3Jvc3MgYWxsIGNvbHVtbnMsIHJlZ2FyZGxlc3Mgb2YgdGhlIHR5cGUuXG4gICAqIENvbHVtbnMgd2l0aCBpZGVudGljYWwgSUQgd2lsbCBzaGFyZSByZXN1bHQgaW4gaWRlbnRpY2FsIHRlbXBsYXRlLlxuICAgKlxuICAgKiBGb3IgZXhhbXBsZSwgaGF2aW5nIGEgaGVhZGVyIGNvbHVtbiBhbmQgYSBmb290ZXIgY29sdW1uIHdpdGggdGhlIHNhbWUgaWQgd2lsbCByZXN1bHQgaW4gdGhlIHNhbWUgY2VsbCBwcmVzZW50YXRpb24gZm9yIGJvdGguXG4gICAqXG4gICAqID4gVGhlIElEIGlzIG1hbmRhdG9yeS4gU29tZSBpbXBsZW1lbnRhdGlvbiBtaWdodCB1c2Ugb3RoZXIgdmFsdWVzIHRvIGF1dG8tZ2VuZXJhdGUgaXQgYW5kIHNvbWUgbWlnaHQgcmVxdWlyZSBpdCBleHBsaWNpdGx5LlxuICAgKiBUaGlzIGlzIHdoYXQgaXQgaXMgb3B0aW9uYWwuXG4gICAqL1xuICBpZD86IHN0cmluZztcbiAgbGFiZWw/OiBzdHJpbmc7XG5cbiAgLyoqXG4gICAqIFRoZSB0eXBlIG9mIHRoZSB2YWx1ZXMgaW4gdGhpcyBjb2x1bW4uXG4gICAqIFRoaXMgaXMgYW4gYWRkaXRpb25hbCBsZXZlbCBmb3IgbWF0Y2hpbmcgY29sdW1ucyB0byB0ZW1wbGF0ZXMsIGdyb3VwaW5nIHRlbXBsYXRlcyBmb3IgYSB0eXBlLlxuICAgKi9cbiAgdHlwZT86IHN0cmluZyB8IFBibENvbHVtblR5cGVEZWZpbml0aW9uO1xuXG4gIC8qKlxuICAgKiBDU1MgY2xhc3MgdGhhdCBnZXQgYXBwbGllZCBvbiB0aGUgaGVhZGVyIGFuZCBjZWxsLlxuICAgKiBZb3UgY2FuIGFwcGx5IHVuaXF1ZSBoZWFkZXIvY2VsbCBzdHlsZXMgdXNpbmcgdGhlIGVsZW1lbnQgbmFtZS5cbiAgICovXG4gIGNzcz86IHN0cmluZztcblxuICAvKipcbiAgICogVGhlIHdpZHRoIGluIHB4IG9yICUgaW4gdGhlIGZvbGxvd2luZyBmb3JtYXQ6ICMjJSBvciAjI3B4XG4gICAqIEV4YW1wbGVzOiAnNTAlJywgJzUwcHgnXG4gICAqL1xuICB3aWR0aD86IHN0cmluZztcbiAgLyoqXG4gICAqIFRoaXMgbWluaW11bSB3aWR0aCBpbiBwaXhlbHNcbiAgICogVGhpcyBpcyBhbiBhYnNvbHV0ZSB2YWx1ZSwgdGh1cyBhIG51bWJlci5cbiAgICovXG4gIG1pbldpZHRoPzogbnVtYmVyO1xuICAvKipcbiAgICogVGhpcyBtYXhpbXVtIHdpZHRoIGluIHBpeGVsc1xuICAgKiBUaGlzIGlzIGFuIGFic29sdXRlIHZhbHVlLCB0aHVzIGEgbnVtYmVyLlxuICAgKi9cbiAgbWF4V2lkdGg/OiBudW1iZXI7XG5cbiAgLyoqXG4gICAqIEEgcGxhY2UgdG8gc3RvcmUgdGhpbmdzLi4uXG4gICAqIFRoaXMgbXVzdCBiZSBhbiBvYmplY3QsIHZhbHVlcyBhcmUgc2hhZG93LWNvcGllZCBzbyBwZXJzaXN0IGRhdGEgYmV0d2VlbiBtdWx0aXBsZSBwbHVnaW5zLlxuICAgKi9cbiAgZGF0YT86IGFueTtcbn1cblxuZXhwb3J0IGludGVyZmFjZSBQYmxNZXRhQ29sdW1uRGVmaW5pdGlvbiBleHRlbmRzIFBibEJhc2VDb2x1bW5EZWZpbml0aW9uIHtcbiAgLyoqXG4gICAqIEEgVW5pcXVlIElEIGZvciB0aGUgY29sdW1uLlxuICAgKi9cbiAgaWQ6IHN0cmluZztcblxuICBraW5kOiAnaGVhZGVyJyB8ICdmb290ZXInO1xuXG4gIC8qKlxuICAgKiBUaGUgaW5kZXggKHplcm8gYmFzZWQpIG9mIHRoZSBoZWFkZXIgcm93IHRoaXMgY29sdW1uIGlzIGF0dGFjaGVkIHRvLCB1c2VkIGZvciBtdWx0aS1oZWFkZXIgc2V0dXAuXG4gICAqIFdoZW4gbm90IHNldCAodW5kZWZpbmVkKSB0aGUgaW5kZXggaXMgY29uc2lkZXJlZCB0aGUgTEFTVCBpbmRleC5cbiAgICovXG4gIHJvd0luZGV4OiBudW1iZXI7XG59XG5cbmV4cG9ydCBpbnRlcmZhY2UgUGJsQ29sdW1uR3JvdXBEZWZpbml0aW9uIGV4dGVuZHMgUGJsQmFzZUNvbHVtbkRlZmluaXRpb24ge1xuICAvKipcbiAgICogQSBVbmlxdWUgSUQgZm9yIHRoZSBjb2x1bW4uXG4gICAqIEF1dG8tZ2VuZXJhdGVkIGZyb20gdGhlIHByb3BlcnR5XG4gICAqL1xuICBpZD86IHN0cmluZztcblxuICAgLyoqXG4gICAqIFRoZSBpbmRleCAoemVybyBiYXNlZCkgb2YgdGhlIGhlYWRlciByb3cgdGhpcyBoZWFkZXIgZ3JvdXAgY29sdW1uIGlzIGF0dGFjaGVkIHRvLCB1c2VkIGZvciBtdWx0aS1oZWFkZXIgc2V0dXAuXG4gICAqL1xuICByb3dJbmRleDogbnVtYmVyO1xuICAvKipcbiAgICogVGhlIHRhYmxlJ3MgY29sdW1uIHRoYXQgaXMgdGhlIGZpcnN0IGNoaWxkIGNvbHVtbiBmb3IgdGhpcyBncm91cC5cbiAgICovXG4gIHByb3A6IHN0cmluZztcblxuICAvKipcbiAgICogVGhlIHRvdGFsIHNwYW4gb2YgdGhlIGdyb3VwIChleGNsdWRpbmcgdGhlIGZpcnN0IGNoaWxkIC0gaS5lLiBwcm9wKS5cbiAgICogVGhlIHNwYW4gYW5kIHByb3AgYXJlIHVzZWQgdG8gZ2V0IHRoZSBjaGlsZCBjb2x1bW5zIG9mIHRoaXMgZ3JvdXAuXG4gICAqIFRoZSBzcGFuIGlzIG5vdCBkeW5hbWljLCBvbmNlIHRoZSBjb2x1bW5zIGFyZSBzZXQgdGhleSBkb24ndCBjaGFuZ2UuXG4gICAqXG4gICAqIEZvciBleGFtcGxlLCBpZiBhIHdlIGhhdmUgYSBzcGFuIG9mIDIgYW5kIHRoZSBjb2x1bW4gYXQgdGhlIDJuZCBwb3NpdGlvbiBpcyBoaWRkZW4gaXQgd2lsbCBzdGlsbCBjb3VudCBhc1xuICAgKiBiZWluZyBzcGFubmVkIGFsdGhvdWdoIHRoZSBVSSB3aWxsIHNwYW4gb25seSAxIGNvbHVtbi4uLiAoYmVjYXVzZSB0aGUgMm5kIGlzIGhpZGRlbi4uLilcbiAgICovXG4gIHNwYW46IG51bWJlcjtcbn1cblxuZXhwb3J0IGludGVyZmFjZSBQYmxDb2x1bW5EZWZpbml0aW9uIGV4dGVuZHMgUGJsQmFzZUNvbHVtbkRlZmluaXRpb24ge1xuICAvKipcbiAgICogQSBVbmlxdWUgSUQgZm9yIHRoZSBjb2x1bW4uXG4gICAqIFdoZSBub3Qgc2V0IChyZWNvbW1lbmQpIGl0IGlzIGF1dG8tZ2VuZXJhdGVkIGJ5IGNvbmNhdGVuYXRpbmcgdGhlIHZhbHVlcyBvZiBgcHJvcGAgYW5kICxcbiAgICogSWYgeW91IHNldCB0aGlzIHZhbHVlIG1hbnVhbGx5LCBtYWtlIHN1cmUgaXQgZG9lcyBub3QgY29uZmxpY3Qgd2l0aCBvdGhlciBjb2x1bW5zIVxuICAgKi9cbiAgaWQ/OiBzdHJpbmc7XG5cbiAgLyoqXG4gICAqIFdoZW4gc2V0LCBkZWZpbmVzIHRoaXMgY29sdW1uIGFzIHRoZSBwcmltYXJ5IGluZGV4IG9mIHRoZSBkYXRhLXNldCB3aXRoIGFsbCB2YWx1ZXMgaW4gdGhpcyBjb2x1bW4gYmVpbmcgdW5pcXVlLlxuICAgKi9cbiAgcEluZGV4PzogYm9vbGVhbjtcblxuICAvKipcbiAgICogVGhlIHByb3BlcnR5IHRvIGRpc3BsYXkgKGZyb20gdGhlIHJvdyBlbGVtZW50KVxuICAgKiBZb3UgY2FuIHVzZSBkb3Qgbm90YXRpb24gdG8gZGlzcGxheSBkZWVwIHBhdGhzLlxuICAgKi9cbiAgcHJvcDogc3RyaW5nO1xuXG4gIGhlYWRlclR5cGU/OiBzdHJpbmcgfCBQYmxDb2x1bW5UeXBlRGVmaW5pdGlvbjtcbiAgZm9vdGVyVHlwZT86IHN0cmluZyB8IFBibENvbHVtblR5cGVEZWZpbml0aW9uO1xuXG4gIC8qKlxuICAgKiBBIHBhdGggdG8gYSBuZXN0ZWQgb2JqZWN0LCByZWxhdGl2ZSB0byB0aGUgcm93IGVsZW1lbnQuXG4gICAqIFRoZSB0YWJsZSB3aWxsIGRpc3BsYXkgYHByb3BgIGZyb20gdGhlIG9iamVjdCByZWZlcmVuY2VkIGJ5IGBwYXRoYC5cbiAgICpcbiAgICogWW91IGNhbiBhbHNvIHVzZSBkb3Qgbm90YXRpb24gZGlyZWN0bHkgZnJvbSBgcHJvcGAuXG4gICAqXG4gICAqIEV4YW1wbGU6XG4gICAqIHByb3A6IFwic3RyZWV0XCJcbiAgICogcGF0aDogWyBcIm15SW5zdGFuY2VcIiwgXCJ1c2VyXCIsIFwiYWRkcmVzc1wiXG4gICAqXG4gICAqIGlzIGlkZW50aWNhbCB0bzpcbiAgICogcHJvcDogXCJteUluc3RhbmNlLnVzZXIuYWRkcmVzcy5zdHJlZXRcIlxuICAgKlxuICAgKi9cbiAgcGF0aD86IHN0cmluZ1tdO1xuXG4gIHNvcnQ/OiBib29sZWFuIHwgUGJsTmdyaWRTb3J0ZXI7XG5cbiAgLyoqXG4gICAqIEEgY3VzdG9tIHByZWRpY2F0ZSBmdW5jdGlvbiB0byBmaWx0ZXIgcm93cyB1c2luZyB0aGUgY3VycmVudCBjb2x1bW4uXG4gICAqXG4gICAqIFZhbGlkIG9ubHkgd2hlbiBmaWx0ZXJpbmcgYnkgdmFsdWUuXG4gICAqIFNlZSBgUGJsRGF0YVNvdXJjZS5zZXRGaWx0ZXJgIGZvciBtb3JlIGluZm9ybWF0aW9uLlxuICAgKi9cbiAgZmlsdGVyPzogRGF0YVNvdXJjZUNvbHVtblByZWRpY2F0ZTtcblxuICAvKipcbiAgICogSW5kaWNhdGVzIGlmIHRoZSB0YWJsZSBpcyBlZGl0YWJsZSBvciBub3QuXG4gICAqIE5vdGUgdGhhdCBhbiBlZGl0YWJsZSBhbHNvIHJlcXVpcmVzIGFuIGVkaXQgdGVtcGxhdGUgdG8gcXVhbGlmeSBhcyBlZGl0YWJsZSwgdGhpcyBmbGFnIGFsb25lIGlzIG5vdCBlbm91Z2guXG4gICAqL1xuICBlZGl0YWJsZT86IGJvb2xlYW47XG5cbiAgcGluPzogJ3N0YXJ0JyB8ICdlbmQnO1xuXG4gIC8vIFRPRE8oMS4wLjApOiByZW1vdmVcbiAgLyoqIEBkZXByZWNhdGVkIEJSRUFLSU5HIENIQU5HRSAxLjAuMCAtIFVzZSBgYWxpYXNgIGluc3RlYWQuICovXG4gIHNvcnRBbGlhcz86IHN0cmluZztcblxuICAvKipcbiAgICogQW4gYWxpYXMgdXNlZCB0byBpZGVudGlmeSB0aGUgY29sdW1uLlxuICAgKiBVc2VmdWwgd2hlbiB0aGUgc2VydmVyIHByb3ZpZGVzIHNvcnQvZmlsdGVyIG1ldGFkYXRhIHRoYXQgZG9lcyBub3QgaGF2ZSBhIDE6MSBtYXRjaCB3aXRoIHRoZSBjb2x1bW4gbmFtZXMuXG4gICAqIGUuZy4gRGVlcCBwYXRoIHByb3BzLCBwcm9wZXJ0eSBuYW1lIGNvbnZlbnRpb24gbWlzbWF0Y2gsIGV0Yy4uLlxuICAgKi9cbiAgYWxpYXM/OiBzdHJpbmc7XG5cbiAgLyoqXG4gICAqIE9wdGlvbmFsIHRyYW5zZm9ybWVyIHRoYXQgY29udHJvbCB0aGUgdmFsdWUgb3V0cHV0IGZyb20gdGhlIGNvbWJpbmF0aW9uIG9mIGEgY29sdW1uIGFuZCBhIHJvdy5cbiAgICogVGhlIHZhbHVlIHJldHVybmVkIGZyb20gdGhpcyB0cmFuc2Zvcm1lciB3aWxsIGJlIHJldHVybmVkIGZyb20gYFBibENvbHVtbi5nZXRWYWx1ZWBcbiAgICovXG4gIHRyYW5zZm9ybT86ICh2YWx1ZTogYW55LCByb3c/OiBhbnksIGNvbD86IFBibENvbHVtbikgPT4gYW55O1xufVxuXG5leHBvcnQgaW50ZXJmYWNlIFBibE1ldGFSb3dEZWZpbml0aW9ucyB7XG4gIHJvd0NsYXNzTmFtZT86IHN0cmluZztcbiAgdHlwZT86ICdyb3cnIHwgJ3N0aWNreScgfCAnZml4ZWQnO1xufVxuLyoqXG4gKiBSZXByZXNlbnQgYSBsaXN0IG9mIG1ldGEgY29sdW1uJ3MgdGhhdCB0b2dldGhlciBmb3JtIGEgTUVUQSBST1cuXG4gKiBJbiBvdGhlciB3b3JkcywgdGhpcyBpcyB0aGUgZGVmaW5pdGlvbiBvZiBhIHJvdywgdXNpbmcgaXQncyBidWlsZGluZyBibG9ja3MgLSB0aGUgY29sdW1ucy5cbiAqXG4gKiA+IEEgcm93IGluIHRoZSB0YWJsZSByZXByZXNlbnRzIGEgcm93IGluIHRoZSBkYXRhc291cmNlLCBBICoqbWV0YSByb3cqKiBkb2VzIG5vdCwgaXQgY2FuIHJlcHJlc2VudCBhbnl0aGluZy5cbiAqIE1ldGEgcm93cyBhcmUgaGVhZGVyLCBmb290ZXIgYW5kIGhlYWRlciBncm91cC5cbiAqL1xuZXhwb3J0IGludGVyZmFjZSBQYmxDb2x1bW5TZXQ8VCBleHRlbmRzIFBibE1ldGFDb2x1bW5EZWZpbml0aW9uIHwgUGJsQ29sdW1uR3JvdXBEZWZpbml0aW9uPiBleHRlbmRzIFBibE1ldGFSb3dEZWZpbml0aW9ucyB7XG4gIHJvd0luZGV4OiBudW1iZXI7XG4gIGNvbHM6IFRbXTtcbn1cblxuLyoqXG4gKiBSZXByZXNlbnQgYSBjb21wbGV0ZSBjb2x1bW4gZGVmaW5pdGlvbiBzZXQgZm9yIGEgdGFibGUuICh0YWJsZSwgaGVhZGVyLCBmb290ZXIgYW5kIGhlYWRlckdyb3VwIGNvbHVtbnMpLlxuICpcbiAqIGBQYmxOZ3JpZENvbHVtbkRlZmluaXRpb25TZXRgIGNvbnRhaW5zIFBPSk8gb2JqZWN0cyAoc2ltcGxlIEpTT04gbGlrZSBvYmplY3RzKSBmb3IgZWFjaCBjb2x1bW4gdHlwZSAoYFBibENvbHVtbkRlZmluaXRpb25gLCBgUGJsTWV0YUNvbHVtbkRlZmluaXRpb25gIGFuZCBgUGJsQ29sdW1uR3JvdXBEZWZpbml0aW9uYClcbiAqIHdoaWNoIGFyZSBsYXRlciB1c2VkIHRvIGNyZWF0ZSBydW50aW1lIGluc3RhbmNlIGZvciBlYWNoIGNvbHVtbiB0eXBlIChgUGJsQ29sdW1uYCwgYFBibE1ldGFDb2x1bW5gIGFuZCBgUGJsQ29sdW1uR3JvdXBgKVxuICpcbiAqIEJlY2F1c2UgYFBibE5ncmlkQ29sdW1uRGVmaW5pdGlvblNldGAgY29udGFpbnMgUE9KTyBvYmplY3RzIGl0IGNhbiBiZSBzZXJpYWxpemVkIGVhc2lseS5cbiAqL1xuZXhwb3J0IGludGVyZmFjZSBQYmxOZ3JpZENvbHVtbkRlZmluaXRpb25TZXQge1xuICB0YWJsZToge1xuICAgIGhlYWRlcj86IFBibE1ldGFSb3dEZWZpbml0aW9ucztcbiAgICBmb290ZXI/OiBQYmxNZXRhUm93RGVmaW5pdGlvbnM7XG4gICAgY29sczogUGJsQ29sdW1uRGVmaW5pdGlvbltdO1xuICB9O1xuICBoZWFkZXI6IFBibENvbHVtblNldDxQYmxNZXRhQ29sdW1uRGVmaW5pdGlvbj5bXTtcbiAgZm9vdGVyOiBQYmxDb2x1bW5TZXQ8UGJsTWV0YUNvbHVtbkRlZmluaXRpb24+W107XG4gIGhlYWRlckdyb3VwOiBQYmxDb2x1bW5TZXQ8UGJsQ29sdW1uR3JvdXBEZWZpbml0aW9uPltdO1xufVxuXG4vKipcbiAqIFJlcHJlc2VudCBhIGNvbXBsZXRlIGNvbHVtbiBzZXQgZm9yIGEgdGFibGUuICh0YWJsZSwgaGVhZGVyLCBmb290ZXIgYW5kIGhlYWRlckdyb3VwIGNvbHVtbnMpLlxuICpcbiAqIGBQYmxOZ3JpZENvbHVtblNldGAgY29udGFpbnMgcnVudGltZSBpbnN0YW5jZXMgb2YgZm9yIGVhY2ggY29sdW1uIHR5cGUgKGBQYmxDb2x1bW5gLCBgUGJsTWV0YUNvbHVtbmAgYW5kIGBQYmxDb2x1bW5Hcm91cGApXG4gKiB3aGljaFxuICovXG5leHBvcnQgaW50ZXJmYWNlIFBibE5ncmlkQ29sdW1uU2V0IHtcbiAgdGFibGU6IHtcbiAgICBoZWFkZXI/OiBQYmxNZXRhUm93RGVmaW5pdGlvbnM7XG4gICAgZm9vdGVyPzogUGJsTWV0YVJvd0RlZmluaXRpb25zO1xuICAgIGNvbHM6IFBibENvbHVtbltdO1xuICB9O1xuICBoZWFkZXI6IFBibENvbHVtblNldDxQYmxNZXRhQ29sdW1uPltdO1xuICBmb290ZXI6IFBibENvbHVtblNldDxQYmxNZXRhQ29sdW1uPltdO1xuICBoZWFkZXJHcm91cDogUGJsQ29sdW1uU2V0PFBibENvbHVtbkdyb3VwPltdO1xuICBncm91cFN0b3JlOiBQYmxDb2x1bW5Hcm91cFN0b3JlO1xufVxuIl19